### ISSUE TITLE
User testimonials (section)

### ISSUE THREAD

**Issue by bryanwillis** [MBIStaffing/website#15]
A few of these could be good. 

Jeff could you write one? Just like 3 sentences.

**Comment by bryanwillis** [comment]
**Example from Employer perspective**

<img width="852" alt="screen shot 2015-08-14 at 1 33 52 pm" src="https://cloud.githubusercontent.com/assets/4042621/19401995/1723ab8a-9224-11e6-916d-e37c328be938.png">

**Background Image to Use:**

![64xk850n3a8uzse6fi11l3vmz](https://cloud.githubusercontent.com/assets/4042621/19402005/280d4992-9224-11e6-851e-fa3c7b203d03.jpeg)

**Comment by classicone2day** [comment]
"MBI is different", I've been looking for a job now for several months and MBI exceeded my expectations by taking all of the guesswork out of the recruiting process. Instead of going into the "big black hole" of job searching, MBI made it personal and treated me like a true professional instead of just a name on a resume.
